### ISSUE TITLE
PBR理论_菲涅尔方程可以用Fresnel-Schlick近似法求得近似解_公式翻译出错_提交Issue

### ISSUE THREAD

**Issue by OctopusLian** [LearnOpenGL-CN/LearnOpenGL-CN#110]
[PBR-原文](https://learnopengl.com/PBR/Theory):FSchlick(h,v,F0)=F0+(1−F0)(1−(h⋅v))5 
[PBR-中文翻译](https://learnopengl-cn.github.io/07%20PBR/01%20Theory/):FSchlick(n,v,F0)=F0+(1−F0)(1−(n⋅v))5
n应该改为h.

**Comment by Duadua** [comment]
这里好像就是平面法线n与观察向量v的夹角，感觉原文也写错了。。。
