### ISSUE TITLE
“变换”章节下的“译注”里介绍四元数的pdf公式有误

### ISSUE THREAD

**Issue by KelvinYJY** [LearnOpenGL-CN/LearnOpenGL-CN#145]
quaternion.pdf，第35页，Lemma 4 证明部分的RHS第二行等号的([t, −u] · [s, −v])应该是([t, u] · [s, v])；第45页，倒数第4行的sin<sup>2</sup>(t)应该是sin<sup>2</sup>(θ)

**Comment by Krasjet** [comment]
下次记得去这里报告啦：https://github.com/Krasjet/quaternion
