### ISSUE TITLE
入门-变换-实践

### ISSUE THREAD

**Issue by Tas-I-te** [LearnOpenGL-CN/LearnOpenGL-CN#181]
您好：
在“GLM”小节，第五个代码块
```
unsigned int transformLoc = glGetUniformLocation(ourShader.ID, "transform");
glUniformMatrix4fv(transformLoc, 1, GL_FALSE, glm::value_ptr(trans));
```
的下方，对`glUniformMatrix4fv`的解释中的第三个参数的描述：
> 第三个参数询问我们我们是否希望对我们的矩阵进行**置换**(Transpose)，也就是说交换我们矩阵的行和列。

这里的“置换”能否翻译为“转置”？在线性代数中，“置换”的英文为（Permutation）

引用：https://zhuanlan.zhihu.com/p/148479500

**Comment by BLumia** [comment]
同济版的线代译法也是转置，[维基百科的译法也是转置](https://zh.wikipedia.org/wiki/%E8%BD%AC%E7%BD%AE%E7%9F%A9%E9%98%B5)，我觉得可以。
