### ISSUE TITLE
关于 PBR/Theory 章节 Normal distribution function 的翻译

### ISSUE THREAD

**Issue by wzhijiang** [LearnOpenGL-CN/LearnOpenGL-CN#210]
章节（英文名）：PBR/Theory
原文地址：https://learnopengl.com/PBR/Theory

问题：关于 Normal distribution function 的翻译，在翻译软件里都会翻译成“正态分布函数”，但是我阅读下来感觉这很容易把我带偏了，所以我想 Normal 是不是翻译成法线呢

对应原文：Normal distribution function 

修复建议（可选）：所以这里是不是应该翻译成 法线分布函数

**Comment by BLumia** [comment]
#127 #199 应该没完全修改完吧

**Comment by wzhijiang** [comment]
这个 issue 重复了，那我关了
