### ISSUE TITLE
网站CI是不是失效了？

### ISSUE THREAD

**Issue by Sefank** [LearnOpenGL-CN/LearnOpenGL-CN#220]
travis-ci.org/travis-ci.com已经不能免费用了，看这个部署记录似乎已经1年没有部署了？是不是考虑要转到Actions上了？

**Comment by BLumia** [comment]
修倒是不难修，不过看上去需要组织所有者才有权限处理... @Krasjet @Geequlim

**Comment by Krasjet** [comment]
fixed
