### ISSUE TITLE
第一章 示例代码不全helloWindow中

### ISSUE THREAD

**Issue by mingtiancai** [LearnOpenGL-CN/LearnOpenGL-CN#253]
![2022-06-06_16-53](https://user-images.githubusercontent.com/13520801/172129734-c2deba98-de53-42fa-8396-9ee87d8852d4.png)
![2022-06-06_16-54](https://user-images.githubusercontent.com/13520801/172129741-30add57c-0917-4dac-9d8e-df5202d64116.png)

**Comment by orbitgw** [comment]
无伤大雅

**Comment by L-Super** [comment]
这是正常的，因为与原英文版保持一致 https://learnopengl.com/Getting-started/Hello-Window
