### ISSUE TITLE
所有的公式都不显示了

### ISSUE THREAD

**Issue by yangzijianGit** [LearnOpenGL-CN/LearnOpenGL-CN#275]
比如说摄像机 欧拉角节点
如果我们把斜边边长定义为1，我们就能知道邻边的长度是，它的对边是。这样我们获得了能够得到x和y方向长度的通用公式，它们取决于所给的角度。我们使用它来计算方向向量的分量：
邻边的长度是 (公式不见了) 对边是（公式不见了）

下面附原文
If we define the hypotenuse to be of length 1 we know from trigonometry (soh cah toa) that the adjacant side's length is cos x/h=cos x/1=cos x
 and that the opposing side's length is sin y/h=sin y/1=sin y
. This gives us some general formulas for retrieving the length in both the x and y sides on right triangles, depending on the given angle. Let's use this to calculate the components of the direction vector.

**Comment by yehu1999** [comment]
应该是网页问题吧？我的就有：
![image](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/114279940/e2ff55da-afa4-4545-8bcd-2077fc06b563)

**Comment by yangzijianGit** [comment]
我是chrome 浏览器。看网页源码 
<p>其中<script type="math/tex">\color{red}R</script>是右向量，<script type="math/tex">\color{green}U</script>是上向量，<script type="math/tex">\color{blue}D</script>是方向向量<script type="math/tex">\color{purple}P</script>是摄像机位置向量。注意，位置向量是相反的，因为我们最终希望把世界平移到与我们自身移动的相反方向。把这个LookAt矩阵作为观察矩阵可以很高效地把所有世界坐标变换到刚刚定义的观察空间。LookAt矩阵就像它的名字表达的那样：它会创建一个看着(Look at)给定目标的观察矩阵。</p>
 
这个我在在线html中无法显示 
![image](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/46264835/e24a4b38-2fbd-4a1a-bb3b-ef1018e213a4)
中的R U D 
在edge浏览器中，发现有span标签生成
<p>其中<span class="MathJax_Preview" style="color: inherit; display: none;"></span><span class="MathJax" id="MathJax-Element-2-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><mstyle mathcolor=&quot;red&quot;><mi>R</mi></mstyle></math>" role="presentation" style="position: relative;"><nobr aria-hidden="true"><span class="math" id="MathJax-Span-166" style="width: 0.963em; display: inline-block;"><span style="display: inline-block; position: relative; width: 0.749em; height: 0px; font-size: 125%;"><span style="position: absolute; clip: rect(1.496em, 1000.75em, 2.509em, -999.997em); top: -2.344em; left: 0em;"><span class="mrow" id="MathJax-Span-167"><span class="mstyle" id="MathJax-Span-168" style="color: red;"><span class="mrow" id="MathJax-Span-169" style="color: red;"><span class="mi" id="MathJax-Span-170" style="font-family: MathJax_Math-italic; color: red;">R</span></span></span></span><span style="display: inline-block; width: 0px; height: 2.349em;"></span></span></span><span style="display: inline-block; overflow: hidden; vertical-align: -0.063em; border-left: 0px solid; width: 0px; height: 1.003em;"></span></span></nobr><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle mathcolor="red"><mi>R</mi></mstyle></math></span></span><script type="math/tex" id="MathJax-Element-2">\color{red}R</script>是右向量，<span class="MathJax_Preview" style="color: inherit; display: none;"></span><span class="MathJax" id="MathJax-Element-3-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><mstyle mathcolor=&quot;green&quot;><mi>U</mi></mstyle></math>" role="presentation" style="position: relative;"><nobr aria-hidden="true"><span class="math" id="MathJax-Span-171" style="width: 1.016em; display: inline-block;"><span style="display: inline-block; position: relative; width: 0.803em; height: 0px; font-size: 125%;"><span style="position: absolute; clip: rect(1.496em, 1000.8em, 2.509em, -999.997em); top: -2.344em; left: 0em;"><span class="mrow" id="MathJax-Span-172"><span class="mstyle" id="MathJax-Span-173" style="color: green;"><span class="mrow" id="MathJax-Span-174" style="color: green;"><span class="mi" id="MathJax-Span-175" style="font-family: MathJax_Math-italic; color: green;">U<span style="display: inline-block; overflow: hidden; height: 1px; width: 0.109em;"></span></span></span></span></span><span style="display: inline-block; width: 0px; height: 2.349em;"></span></span></span><span style="display: inline-block; overflow: hidden; vertical-align: -0.063em; border-left: 0px solid; width: 0px; height: 1.003em;"></span></span></nobr><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle mathcolor="green"><mi>U</mi></mstyle></math></span></span><script type="math/tex" id="MathJax-Element-3">\color{green}U</script>是上向量，<span class="MathJax_Preview" style="color: inherit; display: none;"></span><span class="MathJax" id="MathJax-Element-4-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><mstyle mathcolor=&quot;blue&quot;><mi>D</mi></mstyle></math>" role="presentation" style="position: relative;"><nobr aria-hidden="true"><span class="math" id="MathJax-Span-176" style="width: 1.069em; display: inline-block;"><span style="display: inline-block; position: relative; width: 0.856em; height: 0px; font-size: 125%;"><span style="position: absolute; clip: rect(1.496em, 1000.86em, 2.509em, -999.997em); top: -2.344em; left: 0em;"><span class="mrow" id="MathJax-Span-177"><span class="mstyle" id="MathJax-Span-178" style="color: blue;"><span class="mrow" id="MathJax-Span-179" style="color: blue;"><span class="mi" id="MathJax-Span-180" style="font-family: MathJax_Math-italic; color: blue;">D</span></span></span></span><span style="display: inline-block; width: 0px; height: 2.349em;"></span></span></span><span style="display: inline-block; overflow: hidden; vertical-align: -0.063em; border-left: 0px solid; width: 0px; height: 1.003em;"></span></span></nobr><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle mathcolor="blue"><mi>D</mi></mstyle></math></span></span><script type="math/tex" id="MathJax-Element-4">\color{blue}D</script>是方向向量<span class="MathJax_Preview" style="color: inherit; display: none;"></span><span class="MathJax" id="MathJax-Element-5-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><mstyle mathcolor=&quot;purple&quot;><mi>P</mi></mstyle></math>" role="presentation" style="position: relative;"><nobr aria-hidden="true"><span class="math" id="MathJax-Span-181" style="width: 0.963em; display: inline-block;"><span style="display: inline-block; position: relative; width: 0.749em; height: 0px; font-size: 125%;"><span style="position: absolute; clip: rect(1.496em, 1000.75em, 2.509em, -999.997em); top: -2.344em; left: 0em;"><span class="mrow" id="MathJax-Span-182"><span class="mstyle" id="MathJax-Span-183" style="color: purple;"><span class="mrow" id="MathJax-Span-184" style="color: purple;"><span class="mi" id="MathJax-Span-185" style="font-family: MathJax_Math-italic; color: purple;">P<span style="display: inline-block; overflow: hidden; height: 1px; width: 0.109em;"></span></span></span></span></span><span style="display: inline-block; width: 0px; height: 2.349em;"></span></span></span><span style="display: inline-block; overflow: hidden; vertical-align: -0.063em; border-left: 0px solid; width: 0px; height: 1.003em;"></span></span></nobr><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle mathcolor="purple"><mi>P</mi></mstyle></math></span></span><script type="math/tex" id="MathJax-Element-5">\color{purple}P</script>是摄像机位置向量。注意，位置向量是相反的，因为我们最终希望把世界平移到与我们自身移动的相反方向。把这个LookAt矩阵作为观察矩阵可以很高效地把所有世界坐标变换到刚刚定义的观察空间。LookAt矩阵就像它的名字表达的那样：它会创建一个看着(Look at)给定目标的观察矩阵。</p>
这个有知道为什么吗？

**Comment by yangzijianGit** [comment]
![微信截图_20231010114013](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/46264835/b919d834-6a1b-4a2f-ba8e-25c09d1ac396)

**Comment by yangzijianGit** [comment]
![微信截图_20231010114238](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/46264835/d1a63ac0-bd27-47d8-b9ef-ce6bede7a8e0)
![微信截图_20231010114346](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/46264835/d21b3398-fc5c-4404-a8f7-f360dfb429a0)

**Comment by yangzijianGit** [comment]
这个span 标签是怎么出现的呢？ 为什么chrome没有生成这个标签

**Comment by yangzijianGit** [comment]
是我的浏览器设置导致，打扰了
