### ISSUE TITLE
“变换”Transformations章节中所有公式都没有

### ISSUE THREAD

**Issue by has-7** [LearnOpenGL-CN/LearnOpenGL-CN#277]
![image](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/73536228/4cc49733-d6b6-4e7d-9175-015f9e51ae44)
![image](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/73536228/e49c2b81-6cba-4a29-b088-73ab87a6191a)
没有公式

**Comment by BLumia** [comment]
![image](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/10095765/f08f13ed-6b59-490f-b7c1-5de6a4bba2bb)

无法复现。请检查你的 mathjax 是不是加载失败了。
