### ISSUE TITLE
你好，三角形 小节图形渲染管线流程与原文不一致

### ISSUE THREAD

**Issue by Freemanlai66** [LearnOpenGL-CN/LearnOpenGL-CN#283]
![image](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/77650065/db62c697-313e-4a1f-ac67-f21115cc024c)
![image](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/77650065/e091b634-593f-43f7-b1cc-90e06d34fc9e)

**Comment by Freemanlai66** [comment]
介绍部分也有所变化，比如几何着色器变成了optional，不知道是原作者纠错还是实际管线流程在这几年中发生了变化，初学者不太懂...

**Comment by SuperAoao** [comment]
我在Pull Request： fix issue:你好，三角形 小节图形渲染管线流程与原文不一致 #283 #285 修复了这个问题，确实是几何着色器在前，朋友你看得很仔细🧐 
参考https://www.khronos.org/opengl/wiki/Rendering_Pipeline_Overview
