### ISSUE TITLE
坐标系统小节 翻译改进

### ISSUE THREAD

**Issue by Freemanlai66** [LearnOpenGL-CN/LearnOpenGL-CN#286]
![image](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/77650065/867e1c3c-c364-4c56-a519-a7fe56cd79bf)
![image](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/77650065/c36ac84f-ca93-47cf-8523-ce82348c1e9d)

本小节中对FOV介绍时，原作者提到的doom-style是指类似DOOM的射击游戏的fov设置，一般会高于默认的45（快节奏的FPS游戏，如果FOV过低，容易导致3D眩晕），而不是简单的译成末日风格

**Comment by SuperAoao** [comment]
DOOM 已改为官方译名 毁灭战士
