### ISSUE TITLE
入门-坐标系统 这一段代码多了一个括号

### ISSUE THREAD

**Issue by ringhol** [LearnOpenGL-CN/LearnOpenGL-CN#289]
![image](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/assets/90167007/409602c7-2a09-4ff0-8f69-01a29e55e788)
如图，这里的代码多了一个括号

**Comment by SuperAoao** [comment]
我在pf: fix issue 坐标系统小节 翻译改进 #286 , DOOM翻译为毁灭战士并增加小括号解释 #290 里一并修复了这里
