### ISSUE TITLE
发现一些翻译错误如何处理？

### ISSUE THREAD

**Issue by tomisalready** [LearnOpenGL-CN/LearnOpenGL-CN#30]
发现一些翻译错误如何处理？

**Comment by Geequlim** [comment]
你可以开一个issue反馈
当然欢迎修正并提交PR

**Comment by Geequlim** [comment]
如果您发现教程有任何错误的话，欢迎Fork这个工程并发送Pull Request到 new-theme 分支。如果您不想修改的话，可以点击页面上方的 Issues 按钮提交一个Issue，我们看到后会及时更正。如果是对教程的内容有问题，请先查看原文，如果不是翻译错误的话，请直接在原网站评论区向作者（JoeyDeVries）反馈。
