### ISSUE TITLE
关于 Phong Lighting Model、Phong Shading 的译名问题

### ISSUE THREAD

**Issue by NachtgeistW** [LearnOpenGL-CN/LearnOpenGL-CN#312]
查询资料时得知二者均为裴祥风（越南语 Bùi Tường Phong）提出。它们名字里的 Phong 显然来自“裴祥风”的“风”字。现在教程中的译名全部都为“冯氏XXX”，我认为这是个错译。

我的建议是改为“风氏XXX”，即改 Phong Lighting Model 为“**风氏光照模型**”，改 Phong Shading 为“**风氏着色”。**

另：

据维基百科，

> 越南人名中，主人专属的名（[越南语](https://zh.wikipedia.org/wiki/%E8%B6%8A%E5%8D%97%E8%AF%AD)：tên chính／𠸛正），是较具实际意义的名字，为一般人与人之间相互辨识的依据。越南人较习惯以个人名来称呼一个人，包括正式的场合（如为双名则用后一个字）。例如“阮文明”（Nguyễn Văn Minh），在正式场合人们会称之“明先生”（[越南语](https://zh.wikipedia.org/wiki/%E8%B6%8A%E5%8D%97%E8%AF%AD)：ông Minh／翁明），而不是“阮先生”。

英文模型以 Phong 为名而不是  Bui，大抵是这个原因。

参考：
[越南人名#个人名](https://zh.wikipedia.org/wiki/%E8%B6%8A%E5%8D%97%E4%BA%BA%E5%90%8D#%E5%80%8B%E4%BA%BA%E5%90%8D)

**Comment by BLumia** [comment]
> 查询资料时得知二者均为裴祥风（越南语 Bùi Tường Phong）提出。它们名字里的 Phong 显然来自“裴祥风”的“风”字。现在教程中的译名全部都为“冯氏XXX”，我认为这是个错译。

同意这个说法。

> 我的建议是改为“风氏XXX”，即改 Phong Lighting Model 为“风氏光照模型”，改 Phong Shading 为“风氏着色”。

随后另外查询了下是否有现有资料使用“风氏XXX”的译法，结果未查到使用此方式译法的文献或其它参考资料。我的想法是或许直接原样保留“Phong Shading”，“Phong Lighting Model”名称，以和其它参考作品保持一致？这样读者在参阅其它资料时也能看到相同的描述方式而不会感到困惑。

**Comment by NachtgeistW** [comment]
> > 我的建议是改为“风氏XXX”，即改 Phong Lighting Model 为“风氏光照模型”，改 Phong Shading 为“风氏着色”。
> 
> 随后另外查询了下是否有现有资料使用“风氏XXX”的译法，结果未查到使用此方式译法的文献或其它参考资料。我的想法是或许直接原样保留“Phong Shading”，“Phong Lighting Model”名称，以和其它参考作品保持一致？这样读者在参阅其它资料时也能看到相同的描述方式而不会感到困惑。

我的观点是使用译名+英文原名的方式，比如：风氏着色（英文：Phong Shading）。
在有理有据、考证无误的情况下，我认为自造一个译名是完全OK的，而且方便中文使用者学习与交流；后面立跟英文原名，也能达到您所提出的效果。

**Comment by BLumia** [comment]
> 我的观点是使用译名+英文原名的方式，比如：风氏着色（英文：Phong Shading）。

我觉得也 ok，不过括号的附注应该不用加“英文：”字样了，大家肯定看得出来是英文 :)

有兴趣直接提 PR 吗？

**Comment by NachtgeistW** [comment]
> > 我的观点是使用译名+英文原名的方式，比如：风氏着色（英文：Phong Shading）。
> 
> 我觉得也 ok，不过括号的附注应该不用加“英文：”字样了，大家肯定看得出来是英文 :)
> 
> 有兴趣直接提 PR 吗？

好的，我晚些时候会提交
