### ISSUE TITLE
关于修复笑脸图白边的问题

### ISSUE THREAD

**Issue by jkjkil4** [LearnOpenGL-CN/LearnOpenGL-CN#322]
在 01 Getting Started / 06 Textures 这节中

![image](https://github.com/user-attachments/assets/cc509ae7-1db1-4105-b3b0-a07b3c6dd75a)

如评论区这位所说的，我也测试了一下，learnopengl.com 中新的笑脸图修复了白边的问题

在中文文档修复该问题需要替换以下图片：

- [LearnOpenGL-CN/awesomeface.png](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/blob/086711d4d71d242eb4be0d6ceede6af35e240d86/docs/img/01/06/awesomeface.png) -> [LearnOpenGL/awesomeface.png](https://learnopengl.com/img/textures/awesomeface.png)

- [LearnOpenGL-CN/textures_combined.png](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/blob/086711d4d71d242eb4be0d6ceede6af35e240d86/docs/img/01/06/textures_combined.png) -> [LearnOpenGL/textures_combined.png](https://learnopengl.com/img/getting-started/textures_combined.png)

- [LearnOpenGL-CN/textures_combined2.png](https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/blob/086711d4d71d242eb4be0d6ceede6af35e240d86/docs/img/01/06/textures_combined2.png) -> [LearnOpenGL/textures_combined2.png](https://learnopengl.com/img/getting-started/textures_combined2.png)

由于需要替换多个图片，并且新的运行结果示例的窗口风格不同（新的是 win10 窗口），因此在此开了个 Issue，如果需要的话我可以提交一个 PR

**Comment by BLumia** [comment]
看上去没问题。欢迎直接 PR :)
