### ISSUE TITLE
入门/着色器/GLSL“着色器的开头总是要声明版本...”翻译Issue

### ISSUE THREAD

**Issue by qxly** [LearnOpenGL-CN/LearnOpenGL-CN#37]
入门/着色器/GLSL：
原文：Shaders always begin with a version declaration, followed by a list of input and output variables, uniforms and its main function
翻译：着色器的开头总是要声明版本，接着是输入和输出变量、uniform和main函数。
分析：GLSL可以不声明版本，猜测程序会根据OpenGL32.lib确定一个最低版本。不同版本GLSL可能不同，对应语言的变量、函数也可能不同。且如果要声明版本，必须在首行，否则会编译错误
建议改为：着色器可以用一个版本号开始，接着是输入和输出变量、uniform和main函数。

**Comment by Meow-J** [comment]
嘛，这个到作者那里去反馈啦，而且即便会自动生成，不声明版本也绝对不是推荐的行为。

另外：

> If a `#version`​ directive does not appear at the top, then it assumes 1.10, which is almost certainly not what you want.

见：https://www.opengl.org/wiki/Core_Language_(GLSL)

**Comment by qxly** [comment]
sure，绝对推荐写上版本，教程上例子，如不写#version 330，会有编译错误。
ps：实际开发时考虑兼容性，此版本号会低些。
