### ISSUE TITLE
入门/纹理/练习，“修改片段着色器，仅对笑脸图案进行翻转”问题

### ISSUE THREAD

**Issue by qxly** [LearnOpenGL-CN/LearnOpenGL-CN#40]
要求只对笑脸翻转
参考答案为：
color = mix(texture(ourTexture1, TexCoord), texture(ourTexture2, vec2(1.0 - TexCoord.x, TexCoord.y)), 0.2);
应改为：
color = mix(texture(ourTexture1, TexCoord), texture(ourTexture2, vec2(TexCoord.x, 1.0 - TexCoord.y)), 0.2);

**Comment by Meow-J** [comment]
翻译有点问题，修好了
