### ISSUE TITLE
Tessellation Evaluation Shader的翻译问题

### ISSUE THREAD

**Issue by Meow-J** [LearnOpenGL-CN/LearnOpenGL-CN#41]
见这一篇这里：https://git.io/v6i7e

由于想不出来其它翻译，现在暂时直译成“细分评估着色器”，但这肯定是不对的。

Tessellation是细分没有问题，但是Evaluation在着色器本身的功能上绝对不是“评估”。TES本身的功能是根据细分图元生成器(TPG)提供的数据计算出顶点的坐标。在这里Evaluation的意义类似于`evaluate an expression`里这样，但是翻译成“细分计算着色器”会与Compute Shader(计算着色器)产生混淆，所以还希望一个更好的翻译。

参考：
- https://www.opengl.org/wiki/Tessellation_Evaluation_Shader
- https://www.opengl.org/wiki/Tessellation

**Comment by sinojelly** [comment]
挺好，关注更好的翻译

**Comment by hellokenlee** [comment]
Evaluation 在数学上有求值，计算的意思，我认为可以翻译为 细分求值着色器。

**Comment by Meow-J** [comment]
现在用的是 细分计算着色器，求值曾经考虑过，但这个着色器的目的并不是求出一个值，而是计算出值所代表的坐标等信息。所以我还是用了计算。

**Comment by hellokenlee** [comment]
赞～
