### ISSUE TITLE
入门/着色器/从文件读取，译注1，有不同理解

### ISSUE THREAD

**Issue by qxly** [LearnOpenGL-CN/LearnOpenGL-CN#46]
译注1

实际上把着色器代码保存在文件中适合学习OpenGL的时候，实际开发中最好把一个着色器直接储存为多个字符串，这样具有更高的灵活度。

实际开发，GLSL放在代码中，修改时，程序需要compile，大型程序花费时间很长，灵活度不如写在文件中

**Comment by Meow-J** [comment]
这个译注的作者是 Django，我个人也不赞同这个译注，还是更喜欢将着色器文件分开放。
