### ISSUE TITLE
getting started/coordinate systems/world space，“然后沿着y轴往坐标旋转”等几处问题

### ISSUE THREAD

**Issue by qxly** [LearnOpenGL-CN/LearnOpenGL-CN#47]
1世界空间
原文：
Think of it as transforming a house by scaling it down (it was a bit too large in local space), translating it to a suburbia town and rotating it a bit to the left on the y-axis so that it neatly fits with the neighboring houses. 

翻译：
你可以想象一下，我们需要转换一栋房子，通过将它缩小(因为它在局部坐标系中显得太大了)，将它往郊区的方向平移，然后沿着y轴往坐标旋转。

ps:最后一句，应为“然后沿着y轴往左旋转”

2透视投影
原文:
anything outside the frustum will not end up in the clip space volume and will thus become clipped.

翻译:
任何在这个平截头体的对象最后都不会出现在裁剪空间体积内，并且将会受到裁剪。

ps:应为“任何在这个平截头体**外**的对象...”

3透视投影
原文：
The second parameter sets the aspect ratio which is calculated by dividing the viewport's width by its height. 

翻译：
第二个参数设置了宽高比，由视口的高除以宽

ps：看原文是高/宽，但上面公式是宽/高，感觉公式应该更准确

4进入3D
翻译：
我们会通过将场景沿着z轴正方向平移来实现这个

ps:应为“我们会通过将场景沿着z轴**负**方向平移来实现这个”

5.进入3D
翻译：
OpenGL会将它的深度值和z缓冲进行比较然后如果当前的片段在其它片段之后它将会被丢弃，然后重写

ps：最后应为“否则重写”

**Comment by Meow-J** [comment]
这一节还没有校对，等我之后校对时候再改

**Comment by qxly** [comment]
是否后面的章节都还没校对？

**Comment by Meow-J** [comment]
是的

**Comment by qxly** [comment]
后面发现问题，需要提issues不？还是你后面校对解决？

**Comment by Meow-J** [comment]
都整理在一个Issue里吧，我去开一个

**Comment by qxly** [comment]
ok！

**Comment by Meow-J** [comment]
1、2已在#49 修复

**Comment by Meow-J** [comment]
之前弄完了
