### ISSUE TITLE
翻译问题请来这里提交

### ISSUE THREAD

**Issue by Meow-J** [LearnOpenGL-CN/LearnOpenGL-CN#48]
多个章节的问题请分为多个回复提交，单个章节的多个问题请合并为一个回复提交。

**Comment by qxly** [comment]
1.入门/照相机/Look At，“通过重复计算x和y坐标”应为“通过重复计算x和z坐标”
2.入门/照相机/摄像机类，“每个摄像机系统都有自己的有点和不足”改为“优点和不足”

**Comment by qxly** [comment]
1.光照/光照基础，“和环境光照一样”应为“和漫反射光照一样”
2.光照/光照基础，“因此，如果我们打算把法向量乘以一个模型矩阵，我们就要把模型矩阵左上角的3×3矩阵从模型矩阵中移除(译注：所谓移除就是设置为0)，它是模型矩阵的平移部分(注意，我们也可以把法向量的w分量设置为0，再乘以4×4矩阵；同样可以移除平移)。”,模型矩阵左上角3*3为旋转和缩放，乘以法向量时，正是用这部分，不应移除
3.光照/光照基础，“在环境光照部分”应为“在漫反射光照部分”

**Comment by plumer** [comment]
4.模型/模型加载，“Assimp调用他们的顶点位置数组`mVertices`真有点违反直觉。” -> “Assimp把他们的顶点位置数组称为`mVertices`真有点违反直觉。“我猜原作者的意思是称为mPositions(“位置”)会更好一些。原文：”Assimp calls their vertex position array `mVertices` which isn’t really too intuitive.“

**Comment by iiRecord** [comment]
02 Lighting - 05 Light casters.md
“更具这个修改它的光照”，“更具”应该改为“根据”。

**Comment by zhu-ty** [comment]
投光物一章的第一张图挂了……

**Comment by qxly** [comment]
入门/你好，三角形章节，“通过glVertexAttribPointer调用进行的顶点缓冲对象与顶点属性链接。”，原文“Vertex buffer objects associated with vertex attributes by calls to glVertexAttribPointer.”，建议改为“调用glVertexAttribPointer关联顶点属性的VBO对象”。此处表示存储VBO对象

**Comment by hellokenlee** [comment]
- 光照/投光物 章节 ，定向光-Important绿色框 中间代码格式有误。
- 光照/投光物 章节 ，定向光-Important绿色框 下面，_飞跃_场景 应翻译为漫游( fly through , 原文： If you'd now compile the application and fly through the scene...)
- 光照/复习 章节，词汇表-高氏着色法(Gouraud shading): _树木_  一词应为数目(number, 原文：Produces noticeable artifacts when using a small number of vertices.)
- 光照/复习 章节，词汇表-GLSL uniform数组: ...只是不能被动态调用..._调用_ 一词应翻译为分配(allocated, 原文：...except that they can't be dynamically allocated.)


还有几个地方在看的时候发现有问题，但是忘了在哪了QAQ.

**Comment by hellokenlee** [comment]
建议把ReadTheDoc中的删除或同步到最新版本(ReadTheDoc的翻译版本错误太多。

**Comment by Meow-J** [comment]
readthedocs首页已经链接过来了

**Comment by callmeYe** [comment]
实战/调试，“但一个叫做调试输出(Debug Output)的OpenGL拓展十一个非常游泳的工具”应为“但一个叫做调试输出(Debug Output)的OpenGL拓展是一个非常有用的工具”

**Comment by hellokenlee** [comment]
章节“高级OpenGL-几何着色器-使用几何着色器” 中：图片下面，

> 但我们不是已经学到了所有内容了吗？

原文：

> But didn't we already learn to do all this?

与原文意思不相符，建议译为：

> 但是这些我们不全都学过了吗？

**Comment by mycmessia** [comment]
高级光照法线贴图一章第一个公式错了vec3 rgb_normal = normal * 0.5 - 0.5; // transforms from [-1,1] to [0,1]   应该是 + 0.5

**Comment by hellokenlee** [comment]
章节“模型加载-模型” 中：第一段话，

> 更确切的说，一个模型包含多个网格(Mesh)，一个网格可能带有多个对象。一个别墅，包含一个木制阳台，一个尖顶或许也有一个游泳池，它仍然被加载为一个单一模型。

原文：

> ...that is, a model that contains multiple meshes, possibly with multiple objects. A house, that contains a wooden balcony, a tower and perhaps a swimming pool could still be loaded as a single model. 

与原文意思不相符，尤其是"possibly with multiple objects"的主语是model而非meshes，建议译为：

> 也就是说，一个模型(对象)可以包含多个网格(对象)，甚至包含多个物体。.....他仍然可以被当作一个模型(对象)来加载。

**Comment by hellokenlee** [comment]
章节“高级OpenGL-深度测试-深度缓冲区的可视化”中代码错了，
```glsl
...
float depth = LinearizeDepth(gl_FragCoord.z);
...
```
根据原来的网站，应该为：
```
float depth = LinearizeDepth(gl_FragCoord.z)/far;
```
提交了那么多问题你们真的有修改吗？若不再修改的话请关闭这么issue。

**Comment by Meow-J** [comment]
@hellokenlee 所有的问题都是有修改的，你可以回章节看看或者看下commit，不过单个issue好像有点难以反馈已解决的状态，还是改为多个issue形式吧。

**Comment by hellokenlee** [comment]
Okay~辛苦了~

**Comment by PacinoPan** [comment]
章节 视差贴图 的第二自然段最后一句：
一张简单的砖块表面的**告诉**贴图如下所示
告诉 应该改为 高度

**Comment by Xiangwk** [comment]
章节-高级光照-法线贴图
段落——最后一件事中的代码
vec3 T = normalize(vec3(model * vec4(tangent, 0.0)));
vec3 N = normalize(vec3(model * vec4(tangent, 0.0)));
这里的vec3 N = normalize(vec3(model * vec4(**tangent**, 0.0)));公式中的tangent有误，应为normal！
