### ISSUE TITLE
法线贴图小节看不见图片

### ISSUE THREAD

**Issue by iiRecord** [LearnOpenGL-CN/LearnOpenGL-CN#52]
这里应该有图片的吧，但是看不见。
![image 1](https://cloud.githubusercontent.com/assets/3625222/18422657/4bbb1ac6-78d0-11e6-8299-b246a77f8845.png)

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/18427539/619e682c-78fb-11e6-933e-5c6343a687a6.png)

我这里是可以的，我把图片搬过来试下吧

**Comment by Geequlim** [comment]
原站被电信墙了，链接到原站的图片可能看不到。

2016年9月12日 15:13，"Meow J" <notifications@github.com>写道：

**Comment by iiRecord** [comment]
好吧。我这里公司网络可以翻墙，居然图片都被墙了。
我刚才又试了可以看见图片了。
赞。
