### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by hellokenlee** [LearnOpenGL-CN/LearnOpenGL-CN#59]
章节（英文名）：Advanced-OpenGL  ->  Stencil-testing  ->  Stencil functions 小节
原文地址：[StencilTest](https://learnopengl.com/#!Advanced-OpenGL/Stencil-testing)
当前译为：
>  ref：指定模板测试的引用值。模板缓冲的内容会与这个值对比。
>  mask：指定一个遮罩，在模板测试对比引用值和储存的模板值前，对它们进行按位与（and）操作，初始设置为1。

原文为：
>ref: specifies the reference value for the stencil test. The stencil buffer's content is compared to this value.
mask: specifies a mask that is ANDed with both the reference value and the stored stencil value before the test compares them. Initially set to all 1s.

根据原文意思，reference应该译为参考值而不是引用，mask应该译为掩码而不是遮罩。后面设为1s而不是1。1s就是0xFF的意思，按照官方文档，mask的解释建议译为：
> mask：指定一个掩码值，该掩码值会与参考值和模板的缓冲值分别做按位与操作，按位与操作后的两个结果再按照比较函数做比较。默认情况下该掩码值为全1(对于8位掩码即0xFF)。

题外话：提交isuess太麻烦，加入member的话是加QQ群就可以了吗？

**Comment by Meow-J** [comment]
可以直接发pull request
