### ISSUE TITLE
翻译问题 ( 不好意思又是我...

### ISSUE THREAD

**Issue by hellokenlee** [LearnOpenGL-CN/LearnOpenGL-CN#63]
章节（英文名）：
>  [Advanced-GLSL](https://learnopengl-cn.github.io/04%20Advanced%20OpenGL/08%20Advanced%20GLSL/#_3)

原文地址：
> [https://learnopengl.com/#!Advanced-OpenGL/Advanced-GLSL](https://learnopengl.com/#!Advanced-OpenGL/Advanced-GLSL)

问题：
> 译文： Uniform块布局-最后一段： “在定义uniform块前面添加layout (std140)声明，我们就能告诉OpenGL这个uniform块使用了std140布局。另外还有两种其他的布局可以选择，它们需要我们在填充缓冲之前查询每个偏移量。我们已经了解了分享布局（shared layout）和其他的布局都将被封装（packed）。当使用封装（packed）布局的时候，不能保证布局在别的程序中能够保持一致，因为它允许编译器从uniform块中优化出去uniform变量，这在每个着色器中都可能不同。”
和原文相去甚远， 估计是机器翻译 校对没做好。

对应原文：
> By adding the statement layout (std140) before the definition of the uniform block we tell OpenGL that this uniform block uses the std140 layout. There are two other layouts to choose from that require us to query each offset before filling the buffers. We've already seen the shared layout and the other remaining layout being packed. When using the packed layout, there is no guarantee that the layout remains the same between programs (not shared) because it allows the compiler to optimize uniform variables away from the uniform block which might differ per shader. 

修复建议（可选）：
> 在定义uniform 块前面添加`layout (std140)`的声明表示这个uniform块使用 std140 布局。 另外我们还有两种布局可以选择，但是这两种布局都要求我们在填充缓冲之前查询每一个变量的偏移。 我们已经介绍了共享布局(shared layout)，剩下另一种布局则是封装布局（packed layout）。当我们使用封装布局(pack layout)的时候， OpenGL不保证所有程序的数据布局方式是一样的（也就是不共享），因为该布局允许编译器去优化uniform变量的数据放置方式，而这种优化的结果因不同的Shader而异。

P.S. 我觉得我译得也不是很好，尤其是packed layout是否该译为封装布局有待商议。不过译为打包布局我是拒绝的...

**Comment by Meow-J** [comment]
通知太多了把这个给淹了，重新又改了一下，译名也换掉了，新的译名会更贴切一点，Packed是因为它会优化从而让块的内存占用最小化。
