### ISSUE TITLE
A thank you, and a request

### ISSUE THREAD

**Issue by JoeyDeVries** [LearnOpenGL-CN/LearnOpenGL-CN#64]
Hey everyone at LearnOpenGL-CN!

I didn't know how to properly communicate to you as a group, so I'm hi-jacking the ticket system for this. But I want to thank you for the translation effort, you did an amazing job and I'm positively surprised how you've managed to capture the look and feel of the site's content. Great stuff!

I noticed you were hosting all translations on a new URL so I've updated the translation references on LearnOpenGL.

Also, I have a small request: would you be so kind to include the original Patreon button/link you can find on the LearnOpenGL website somewhere on the Chinese translation website? I'm sure there's some number of Chinese readers that want to help contribute to new and improved LearnOpenGL content that then propagates to the translated version :-)

**Comment by Meow-J** [comment]
sure

**Comment by Meow-J** [comment]
Done. I added a link to your Patreon on the top-right corner of the pages and a little notice on the front page.

**Comment by JoeyDeVries** [comment]
Thank you!

**Comment by Meow-J** [comment]
BTW, when you update your tutorials, could you keep a list of what you update in the future so that we can update our translations accordingly? You know, keeping track of such a large project is nearly impossible.

**Comment by JoeyDeVries** [comment]
Agreed, I don't have any CMS versioning system, but I've been planning to create a _last-update_ item somewhere close to the title of each tutorial. That could be a good indication of change.
