### ISSUE TITLE
点阴影文章代码有一处和原文不一样

### ISSUE THREAD

**Issue by pengchengo** [LearnOpenGL-CN/LearnOpenGL-CN#85]
#version 330 core
in vec4 FragPos;

uniform vec3 lightPos;
uniform float far_plane;

void main()
{
    // get distance between fragment and light source
    float lightDistance = length(FragPos.xyz - lightPos);

    // map to [0;1] range by dividing by far_plane
    lightDistance = lightDistance / far_plane;

    // Write this as modified depth
    gl_FragDepth = gl_FragCoord.z;
}
应该是gl_FragDepth = lightDistance;

**Comment by Meow-J** [comment]
这节还没重写，目前4-9之后的都会与原文有点不同，等我重写到那一节的时候一起改吧
