### ISSUE TITLE
变换章节数学公式显示不正确

### ISSUE THREAD

**Issue by sike2017** [LearnOpenGL-CN/LearnOpenGL-CN#92]

**Comment by sike2017** [comment]
变换章节数学公式显示不正确

**Comment by Meow-J** [comment]
具体是哪里呢

**Comment by sike2017** [comment]
一直没有看邮箱，今天才看到，现在网站显示是正常的，之前显示[MathError]，也可能是我浏览器的问题。。。

________________________________
发件人: Meow J <notifications@github.com>
发送时间: 2018年2月20日 6:25:33
收件人: LearnOpenGL-CN/LearnOpenGL-CN
抄送: sike2017; Author
主题: Re: [LearnOpenGL-CN/LearnOpenGL-CN] 变换章节数学公式显示不正确 (#92)


具体是哪里呢

―
